CREATE DATABASE testdb;
CREATE USER admin WITH PASSWORD 'admin123' SUPERUSER;
CREATE USER user1 WITH PASSWORD 'user1';
CREATE USER user2 WITH PASSWORD 'user2';

GRANT ALL PRIVILEGES ON DATABASE testdb TO user1;
GRANT ALL PRIVILEGES ON DATABASE testdb TO user2;
